### ISSUE TITLE
Default value for PhysicalResourceID causes functions that support `Update` to get a `Delete` request during update

### ISSUE THREAD

**Issue by guss77** [LukeMizuhashi/cfn-response#2]
As described [here](https://stackoverflow.com/questions/50599602/updating-custom-resources-causes-them-to-be-deleted), when the function calling `send()` does not provide a physical resource ID argument (which is very common practice - I've seen only a handful of examples that pass a 5th argument), `cfn-response` uses the log stream name, which is more or less a random value that updates for almost every call.

The result is that during an update, CloudFormation decides that because the physical resource ID of the custom resource had updated, the "old resource" needs to be deleted. This causes a lot of confusion to developers that want to support updatable custom resources.

A better default value would be to use the CloudFormation provided PhysicalResourceID (if provided) and only fall back to the log stream name if neither the function developer nor CloudFormation provided a physical resource ID. 

This will by default cause the behavior for `Update` requests to be consistent with most other CloudFormation resources and will only require more work from the developer if they want to implement "potentially replacing update operations" that work with the CloudFormation "create and update all resources before removing replaced resources" - which I expect to be very rare.

**Comment by LukeMizuhashi** [comment]
Hey'o! Thanks for the pull request.

I'm not actively developing this code. ( Amazon is, though--hosted somewhere else. ) This is just a convenience node module I made for myself, a copy-paste job of whatever the official code is from Amazon.

To actively develop this code, please fork the repo and open a dialogue with Amazon.

Best!
